import { StrictMode, useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowLeft, ArrowRight, Check, Menu, X } from 'lucide-react'
import './styles.css'

type ProductKey = 'aphia' | 'ilmia'
type Product = { name: string; kicker: string; title: string; intro: string; image: string; accent: string; cta: string; ctaHref: string; secondary: string; secondaryHref: string; features: string[] }

const products: Record<ProductKey, Product> = {
  aphia: { name: 'APHIA Care', kicker: 'Système de gestion officinale', title: 'Votre pharmacie, enfin lisible.', intro: 'APHIA Care réunit les stocks, la vente, les finances et les équipes dans un seul espace pensé pour les réalités de l’officine au Sénégal.', image: '/aphia-care.png', accent: 'coral', cta: 'Ouvrir aphia.care', ctaHref: 'https://aphia.care', secondary: 'Book a demo', secondaryHref: 'mailto:contact@shifatek.com?subject=Demande%20de%20d%C3%A9monstration%20APHIA%20Care', features: ['Stocks par lot, expiration et emplacement', 'Réception, transferts, imports et gestion du stock négatif', 'Point de vente, paniers, paiements et clôture de caisse', 'Crédits patients, comptes mutuelles, créances et dépenses', 'Alertes, historique des ventes et auditabilité complète'] },
  ilmia: { name: 'Ilmia', kicker: 'Apprentissage médical augmenté', title: 'Apprendre en faisant.', intro: 'Ilmia transforme les cours de médecine en expériences actives : défis, simulations et parcours d’entraînement construits avec les experts.', image: '/ilmia-learning.png', accent: 'mint', cta: 'Découvrir Ilmia', ctaHref: 'https://contact.shifatek.com', secondary: 'Rejoindre la cohorte pilote', secondaryHref: 'https://contact.shifatek.com', features: ['Studio de contenus jouables validés par des experts', 'Arena : ligues et tournois inter-facultés', 'Patient : simulation conversationnelle', 'Coach : tutorat adaptatif et répétition espacée'] },
}
const navItems = [['Mission', '#mission'], ['APHIA Care', '/aphia'], ['Ilmia', '/ilmia']] as const
const v2Features = ['Dossier patient clinique', 'Vérificateur d’interactions médicamenteuses', 'Comptabilité avancée et suivi des impayés', 'Réseau inter-pharmacies', 'Analytique métier et assistant IA', 'Sauvegarde, export et journal d’audit immuable', 'Publicité fournisseurs et gestion RH']

function Reveal({ children, className = '' }: { children: ReactNode; className?: string }) { const [visible, setVisible] = useState(false); const ref = useRef<HTMLDivElement>(null); useEffect(() => { if (!ref.current) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setVisible(true); observer.disconnect() } }, { threshold: .1 }); observer.observe(ref.current); return () => observer.disconnect() }, []); return <div ref={ref} className={`reveal ${visible ? 'in' : ''} ${className}`}>{children}</div> }
function Logo() { return <a href="/" className="logo" aria-label="Shifatek, accueil"><span className="logo-mark" aria-hidden="true">S</span><span className="logo-word">Shifa<span>tek</span></span></a> }
function Header() { const [open, setOpen] = useState(false); const product = window.location.pathname !== '/'; return <header><div className="wrap nav"><Logo /><nav id="main-navigation" className={open ? 'nav-links open' : 'nav-links'} aria-label="Navigation principale">{navItems.map(([label, href]) => <a key={href} href={product && href.startsWith('#') ? `/${href}` : href} onClick={() => setOpen(false)}>{label}</a>)}<a className="nav-cta" href={product ? '/#contact' : '#contact'} onClick={() => setOpen(false)}>Nous contacter</a></nav><button className="burger" aria-label={open ? 'Fermer le menu' : 'Ouvrir le menu'} aria-expanded={open} aria-controls="main-navigation" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></header> }
function Actions({ data }: { data: Product }) { return <div className="hero-actions"><a className="btn-primary" href={data.ctaHref} target="_blank" rel="noreferrer">{data.cta} <ArrowRight aria-hidden="true" /></a><a className="btn-text" href={data.secondaryHref} target={data.secondaryHref.startsWith('mailto:') ? undefined : '_blank'} rel={data.secondaryHref.startsWith('mailto:') ? undefined : 'noreferrer'}>{data.secondary} <ArrowRight aria-hidden="true" /></a></div> }
function ContactForm() { const [sent, setSent] = useState(false); const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setSent(true) }; return <form className="contact-form" onSubmit={submit}><div className="form-row"><label>Nom<input name="name" autoComplete="name" required /></label><label>E-mail<input name="email" type="email" autoComplete="email" required /></label></div><label>Organisation<input name="company" autoComplete="organization" /></label><label>Votre message<textarea name="message" required /></label><button className="btn-primary" type="submit">Envoyer la demande <ArrowRight aria-hidden="true" /></button>{sent && <p className="form-note" role="status"><Check aria-hidden="true" /> Merci. Votre demande a bien été préparée.</p>}</form> }
function Home() { return <><Header /><main><section className="home-hero"><div className="wrap home-hero-grid"><Reveal><span className="eyebrow">Santé digitale · Dakar</span><h1>Des outils qui prennent soin du <em>réel.</em></h1><p className="hero-copy">Shifatek construit des produits numériques pour celles et ceux qui font avancer la santé en Afrique de l’Ouest.</p><div className="hero-actions"><a className="btn-primary" href="#produits">Voir nos produits <ArrowRight aria-hidden="true" /></a><a className="btn-text" href="#mission">Notre conviction <ArrowRight aria-hidden="true" /></a></div></Reveal><Reveal className="hero-statement"><span>01</span><p>Observer avant de construire.<br /><strong>Construire pour durer.</strong></p></Reveal></div></section><section className="statement" id="mission"><div className="wrap statement-grid"><Reveal><span className="eyebrow">Notre manière</span><h2>La technologie commence par une conversation.</h2></Reveal><Reveal><p className="large-copy">Nous partons des gestes quotidiens, des contraintes de connexion, des équipes et des patients. Puis nous dessinons des systèmes simples à utiliser, solides dans le temps et ancrés localement.</p></Reveal></div></section><section className="products-section" id="produits"><div className="wrap"><Reveal className="section-intro"><span className="eyebrow">Produits Shifatek</span><h2>Deux façons de faire avancer la santé.</h2></Reveal><div className="product-list">{(['aphia', 'ilmia'] as ProductKey[]).map((key, index) => <Reveal className={`product-row ${products[key].accent}`} key={key}><div className="product-index">0{index + 1}</div><div className="product-copy"><span className="eyebrow">{products[key].kicker}</span><h3>{products[key].name}</h3><p>{products[key].intro}</p><a className="btn-text" href={`/${key}`}>Explorer <ArrowRight aria-hidden="true" /></a></div><img src={products[key].image} alt={`Équipe utilisant ${products[key].name}`} /></Reveal>)}</div></div></section><section className="contact-section" id="contact"><div className="wrap contact-grid"><Reveal><span className="eyebrow">Parlons-en</span><h2>Un problème à résoudre ?</h2><p>Présentez-nous votre contexte. Nous aimons commencer par écouter.</p></Reveal><ContactForm /></div></section></main><Footer /></> }
function ProductPage({ product }: { product: ProductKey }) { const data = products[product]; const aphia = product === 'aphia'; return <><Header /><main className={`product-page ${data.accent}`}><section className="product-hero"><div className="wrap product-hero-grid"><Reveal><a href="/" className="back-link"><ArrowLeft aria-hidden="true" /> Shifatek</a><span className="eyebrow">{data.kicker}</span><h1>{data.title}</h1><p>{data.intro}</p><Actions data={data} /></Reveal><Reveal><img className="product-hero-image" src={data.image} alt={`Présentation de ${data.name}`} /></Reveal></div></section><nav className="section-nav" aria-label={`Sections ${data.name}`}><div className="wrap"><a href="#fonctionnalites">Fonctionnalités</a>{aphia && <a href="#avenir">À venir</a>}<a href="#contact">Parlons-en</a></div></nav><section className="capabilities" id="fonctionnalites"><div className="wrap"><Reveal className="section-intro"><span className="eyebrow">Aujourd’hui</span><h2>Tout ce dont votre équipe a besoin, au même endroit.</h2></Reveal><div className="capability-grid">{data.features.map((feature, i) => <Reveal className="capability" key={feature}><span>0{i + 1}</span><Check aria-hidden="true" /><p>{feature}</p></Reveal>)}</div></div></section>{aphia && <section className="roadmap" id="avenir"><div className="wrap roadmap-grid"><Reveal><span className="eyebrow">Demain · APHIA V2</span><h2>Une plateforme qui grandit avec votre officine.</h2><p>Ces fonctionnalités sont notre feuille de route : elles prolongent la base opérationnelle d’APHIA Care vers une vision plus clinique, collaborative et intelligente.</p></Reveal><Reveal className="roadmap-list">{v2Features.map((feature, i) => <div key={feature}><span>0{i + 1}</span><p>{feature}</p></div>)}</Reveal></div></section>}<section className="contact-section" id="contact"><div className="wrap contact-grid"><Reveal><span className="eyebrow">Échangeons</span><h2>Prêt à faire le prochain pas ?</h2><p>Une démo, une question ou un contexte particulier : écrivez-nous.</p></Reveal><ContactForm /></div></section></main><Footer /></> }
function Footer() { return <footer><div className="wrap footer-grid"><Logo /><div><a href="/#mission">Mission</a><a href="/aphia">APHIA Care</a><a href="/ilmia">Ilmia</a></div><small>© 2026 Shifatek · Dakar, Sénégal</small></div></footer> }
function App() { const path = window.location.pathname.replace(/\/$/, ''); return path === '/aphia' ? <ProductPage product="aphia" /> : path === '/ilmia' ? <ProductPage product="ilmia" /> : <Home /> }
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
