import { StrictMode, useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowLeft, ArrowRight, Check, Menu, X } from 'lucide-react'
import './styles.css'

type ProductKey = 'aphia' | 'ilmia'

const products: Record<ProductKey, { name: string; kicker: string; title: string; intro: string; image: string; color: string; features: string[]; metrics: string[]; cta: string }> = {
  aphia: {
    name: 'APHIA Care', kicker: 'Santé digitale · MVP en production', title: 'La pharmacie, pilotée avec clarté.',
    intro: 'Un système de gestion intégré pensé pour les officines sénégalaises : rapide, traçable et résilient, même quand la connexion ne l’est pas.', image: '/aphia-care.png', color: 'coral',
    features: ['Stocks par lot et date d’expiration', 'Point de vente et bons IPM', 'Finance, marges et créances en temps réel', 'Historique complet et audit trail'], metrics: ['50 % de temps gagné en caisse', '< 100 ms pour retrouver un produit', '100 % des mouvements tracés'], cta: 'Demander une démonstration',
  },
  ilmia: {
    name: 'Ilmia', kicker: 'Apprentissage · en construction', title: 'Le savoir médical devient une pratique.',
    intro: 'L’écosystème d’e-sport cérébral qui transforme les supports de cours en défis interactifs, simulations cliniques et parcours de maîtrise personnalisés.', image: '/ilmia-learning.png', color: 'mint',
    features: ['Ilmia Studio : contenus jouables validés par des experts', 'Ilmia Arena : ligues et tournois inter-facultés', 'Ilmia Patient : simulation conversationnelle', 'Ilmia Coach : tutorat adaptatif et répétition espacée'], metrics: ['12–15 k étudiants de médecine au Sénégal', '5 modules complémentaires', 'Une pédagogie ancrée localement'], cta: 'Rejoindre la cohorte pilote',
  },
}

const navItems = [['Mission', '#mission'], ['APHIA Care', '/aphia'], ['Ilmia', '/ilmia']] as const
const values = [['Rigueur', 'Des produits testés dans les conditions réelles du terrain.'], ['Accessibilité', 'Des outils pensés pour une connectivité variable.'], ['Impact local', "Des solutions qui répondent aux besoins de l'Afrique de l'Ouest."], ['Innovation', "L'IA et le digital mis au service de la santé."]]

function Reveal({ children, className = '' }: { children: ReactNode; className?: string }) { const [visible, setVisible] = useState(false); const ref = useRef<HTMLDivElement>(null); useEffect(() => { if (!ref.current) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setVisible(true); observer.disconnect() } }, { threshold: .12 }); observer.observe(ref.current); return () => observer.disconnect() }, []); return <div ref={ref} className={`reveal ${visible ? 'in' : ''} ${className}`}>{children}</div> }

function Header() { const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false); useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 30); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, []); return <header className={scrolled ? 'scrolled' : ''}><div className="wrap nav"><a href="/" className="logo">Shifa<span>tek</span></a><nav id="main-navigation" className={open ? 'nav-links open' : 'nav-links'} aria-label="Navigation principale">{navItems.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)}>{label}</a>)}<a href="#contact" className="nav-cta" onClick={() => setOpen(false)}>Nous contacter</a></nav><button className="burger" aria-label={open ? 'Fermer le menu' : 'Ouvrir le menu'} aria-expanded={open} aria-controls="main-navigation" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></header> }

function ContactForm() { const [sent, setSent] = useState(false); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true) }; return <form onSubmit={submit} className="contact-form">{[['name', 'Nom', 'text', true], ['email', 'E-mail', 'email', true], ['company', 'Entreprise (facultatif)', 'text', false]].map(([id, label, type, required]) => <div className="field" key={id as string}><label htmlFor={id as string}>{label as string}</label><input id={id as string} name={id as string} type={type as string} required={required as boolean} /></div>)}<div className="field"><label htmlFor="message">Message</label><textarea id="message" name="message" required /></div><button type="submit" className="btn-primary">Envoyer le message</button>{sent && <p className="form-note" role="status"><Check aria-hidden="true" /> Merci ! Votre message est prêt à être traité.</p>}</form> }

function ProductCard({ product }: { product: ProductKey }) { const data = products[product]; return <Reveal className={`product-card ${data.color}`}><img src={data.image} alt={`Illustration de ${data.name}`} /><div className="product-card-body"><span className="tag">{data.kicker}</span><h3>{data.name}</h3><p>{data.intro}</p><a className="btn-text" href={`/${product}`}>Explorer le produit <ArrowRight aria-hidden="true" /></a></div></Reveal> }

function Home() { return <><Header /><main id="top"><section className="hero"><div className="hero-glow" /><div className="wrap hero-inner"><Reveal><span className="eyebrow">Santé digitale · Afrique de l'Ouest</span><h1>La technologie de santé, pensée <em>depuis le terrain</em>.</h1><p>Shifatek conçoit des outils de santé digitale et des solutions innovantes pour l'Afrique de l'Ouest — en partant des besoins réels des pharmacies, des soignants et des étudiants.</p><div className="hero-actions"><a href="#mission" className="btn-primary">Découvrir notre mission</a><a href="#produits" className="btn-text">Voir nos solutions <ArrowRight aria-hidden="true" /></a></div></Reveal><div className="hero-note"><span>01</span><p>Des problèmes observés.<br /><strong>Des solutions qui restent.</strong></p></div></div></section><section className="band" id="mission"><div className="wrap split"><Reveal className="content"><span className="eyebrow">Notre conviction</span><h2>Partir des besoins réels, pas importer des solutions toutes faites.</h2><p className="lead">Chaque produit Shifatek naît d’un problème observé directement au Sénégal — dans une pharmacie, une faculté de médecine, une entreprise — et se construit avec les personnes concernées.</p><a href="#produits" className="inline-link">Découvrir notre approche <ArrowRight aria-hidden="true" /></a></Reveal><Reveal className="quote-card"><span>“</span><p>La bonne technologie est celle qui s’efface derrière l’usage.</p><small>— Shifatek, Dakar</small></Reveal></div></section><section className="band products-band" id="produits"><div className="wrap"><Reveal className="section-head"><span className="eyebrow">Nos solutions</span><h2>Une mission, deux terrains d’action.</h2><p>Des outils conçus localement pour produire un impact mesurable.</p></Reveal><div className="products"><ProductCard product="aphia" /><ProductCard product="ilmia" /></div></div></section><section className="band light" id="apropos"><div className="wrap"><Reveal className="section-head"><span className="eyebrow">Notre manière de faire</span><h2>Construire utile, avec exigence.</h2></Reveal><div className="values">{values.map(([title, text]) => <Reveal className="value" key={title}><h3>{title}</h3><p>{text}</p></Reveal>)}</div></div></section><section className="band" id="contact"><div className="wrap contact-grid"><Reveal className="contact-info"><span className="eyebrow">Parlons-en</span><h2>Construisons la santé digitale de demain, ensemble.</h2><p>Un projet, un partenariat, une formation pour vos équipes ? Écrivez-nous.</p><div className="contact-meta"><div><small>Basés à</small><span>Dakar, Sénégal</span></div><div><small>E-mail</small><a href="mailto:contact@shifatek.com">contact@shifatek.com</a></div></div></Reveal><ContactForm /></div></section></main><Footer /></> }

function ProductPage({ product }: { product: ProductKey }) { const data = products[product]; return <><Header /><main className={`product-page ${data.color}`}><section className="product-hero"><div className="wrap product-hero-grid"><Reveal><a href="/" className="back-link"><ArrowLeft aria-hidden="true" /> Retour à Shifatek</a><span className="eyebrow">{data.kicker}</span><h1>{data.title}</h1><p>{data.intro}</p><a href="#contact" className="btn-primary">{data.cta}</a></Reveal><Reveal><img className="product-hero-image" src={data.image} alt={`Équipe utilisant ${data.name}`} /></Reveal></div></section><section className="band light product-detail"><div className="wrap"><Reveal className="section-head"><span className="eyebrow">Ce que le produit permet</span><h2>Un système pensé autour de vos décisions.</h2></Reveal><div className="feature-grid">{data.features.map((feature) => <Reveal className="feature" key={feature}><Check aria-hidden="true" /><p>{feature}</p></Reveal>)}</div><div className="metrics">{data.metrics.map((metric) => <Reveal className="metric" key={metric}><strong>{metric}</strong></Reveal>)}</div></div></section><section className="band" id="contact"><div className="wrap contact-grid"><Reveal className="contact-info"><span className="eyebrow">Échangeons</span><h2>Prêt à faire le prochain pas ?</h2><p>Présentez-nous votre contexte. Nous vous répondrons avec une proposition adaptée.</p></Reveal><ContactForm /></div></section></main><Footer /></> }
function Footer() { return <footer><div className="wrap foot"><a href="/" className="logo">Shifa<span>tek</span></a><div className="foot-links"><a href="/#mission">Mission</a><a href="/aphia">APHIA Care</a><a href="/ilmia">Ilmia</a><a href="/#contact">Contact</a></div><small>© 2026 Shifatek — Dakar, Sénégal.</small></div></footer> }
function App() { const path = window.location.pathname.replace(/\/$/, ''); return path === '/aphia' ? <ProductPage product="aphia" /> : path === '/ilmia' ? <ProductPage product="ilmia" /> : <Home /> }
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
